### ISSUE TITLE
Repeated objects are created in the database with different primary keys

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/wikithingsdb#4]
Originally raised by @michaelsilver: When inserting into the database with a `relationship()` by using the `.append()` function in `create.py`, repeated objects are created in the database with different primary keys.

To fix this:

You need to add uniqueness constraints to `DbpediaClass`, `WikiClass`, and `Type` so that only one of each gets created. I would also add an index to speed up queries. Here's an example:

```python
class Type(Base):
    __tablename__ = "types"

    id = Column(Integer, primary_key=True)
    type = Column(String(50), unique=True, index=True) # note the index & unique params

    def __init__(self, type):
        self.type = type

    def __repr__(self):
        return '<Type: %s>' % self.type
```

Next, you need a `get_or_create` function whenever you want to create an object with a uniqueness constraint. It should be similar to:

```python
def get_or_create_cheese(cheese_type):
    try:
        with db.session.begin_nested():
            cheese = Cheese(type=cheese_type)
        db.session.add(cheese)
    except IntegrityError:
        cheese = Cheese.query.filter(Cheese.type==cheese_type).first()
    return cheese
```

The full explanation is [here](http://tttv-engineering.tumblr.com/post/80984647963/flask-sqlalchemy-get-or-create). You get an IntegrityError exception when the row already exists because of the uniqueness constraint.

**Comment by michaelsilver** [comment]
Hmm... having some trouble with the `get_or_create()` function (see commit e3958f9a86a7983fe9630733f14ccc1738006f7b). Getting the following error:
```
**************FINAL COMMIT COMMIT COMMIT **************
Traceback (most recent call last):
  File "/scratch/msilver/.virtualenvs/wikithingsdb/bin/wikithingsdb", line 9, in <module>
    load_entry_point('wikithingsdb==0.1.0', 'console_scripts', 'wikithingsdb')()
  File "/afs/csail.mit.edu/u/m/msilver/wikithingsdb/wikithingsdb/create.py", line 155, in main
    session.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 790, in commit
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 390, in commit
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 214, in _assert_active
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'organization' for key 'ix_classes_class_name'") [SQL: u'INSERT INTO classes (class_name) VALUES (%s)'] [parameters: ('organization',)]
```
I have tried using `session.flush()` and `session.rollback()` in the except block without luck. As I understand, the `begin_nested()` block should be handling flushing and rolling back automatically... any ideas?

**Comment by alvaromorales** [comment]
Errr I totally thought that `begin_nested()` in a `with` block automatically rolled back upon an exception. Looks like the issue might be around auto-flushing (`raised as a result of Query-invoked autoflush`).

Try `session = Session(autocommit=False)`, or "using a session.no_autoflush block".

More docs here http://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#session-begin-nested
